### ISSUE TITLE
Looks interesting! Curious why you chose rubicon over pyobjc?

### ISSUE THREAD

**Issue by RhetTbull** [eduardohleite/applepy#18]
Hi. Sorry -- not really an issue but Discussions wasn't enabled on the repo. This looks very interesting -- I do a lot of Mac-specific stuff in Python and have been thinking of doing something like this for a while. I haven't had a chance to try this out yet but look forward to playing with applepy.  All my Mac-native stuff has been using [pyobjc](https://pypi.org/project/pyobjc/) and I've not used rubicon.  I'm curious why you chose rubicon instead of pybojc?

**Comment by eduardohleite** [comment]
Hello. That's okay. pyobjc is definitely more mature. I ended up choosing rubicon instead because I also wanted to support iOS and pyobjc officially supports Mac only. Rubicon + briefcase work great on iPhone/iPad.

**Comment by RhetTbull** [comment]
Ah, that makes sense. I've not tried any iOS development with Python.
